### ISSUE TITLE
EPERM in version 3.7.0, error related to adal node package

### ISSUE THREAD

**Issue by Dayof** [strongloop/loopback-connector-mssql#223] opened 2020-01-23 18:24 UTC
## Steps to reproduce

```powershell
npm i -g @loopback/cli
npm install loopback-connector-mssql@3.7.0 --save
```

## Current Behavior

```
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\nodejs\npm\node_modules\loopback-connector-mssql\node_modules\.adal
node.DELETE\node_modules\@types 
npm ERR! dest C:\nodejs\npm\node_modules\loopback-connector-mssql\node_modules\adal
node\node_modules\@types
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\nodejs\npm\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'C:\nodejs\npm\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\nodejs\npm\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'C:\nodejs\npm\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\nodejs\npm\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'C:\nodejs\npm\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\nodejs\\npm\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types',                                                                                                                                           npm ERR!     dest: 'C:\\nodejs\\npm\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, rename 'C:\\nodejs\\npm\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types' -> 'C:\\nodejs\\npm\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types'", 
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM', 
npm ERR!   syscall: 'rename',  
npm ERR!   path: 'C:\\nodejs\\npm\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types',                                                                                                                                             npm ERR!   dest: 'C:\\nodejs\\npm\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types',
npm ERR!   parent: 'loopback-connector-mssql'
npm ERR! } 
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the 
npm ERR! permissions of the file and its containing directories, or try running 
npm ERR! the command again as root/Administrator. 
npm ERR! A complete log of this run can be found in: 
npm ERR!     C:\nodejs\npm-cache\_logs\2020-01-23T18_06_34_830Z-debug.log
```

## Expected Behavior

I was expecting to install the package in my local project, I tried with -g too but I had the same problem. The last version didn't show this problem, the installation with **loopback-connector-mssql@3.6.0** works.

## Additional information

```powershell
win32 x64 12.14.1
test@1.0.0 C:\temp\test
+-- @loopback/boot@1.7.1
+-- @loopback/context@1.25.1
+-- @loopback/core@1.12.1
+-- @loopback/openapi-v3@1.11.0
+-- @loopback/repository@1.17.0
+-- @loopback/rest@1.25.1
+-- @loopback/rest-explorer@1.4.7
`-- @loopback/service-proxy@1.3.14
```

**Comment by achrinza** [comment] 2020-02-22 14:37
Does `npm ci` resolve the issue?

**Comment by nsabourin** [comment] 2020-03-03 18:08
@achrinza I have the same issue and it doesn't resolve it

**Comment by LuiguiBalarezo** [comment] 2020-03-03 22:01
I ALSO HAVE THE SAME PROBLEM :v 

npm WARN npm npm does not support Node.js v13.9.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN zventas-api-loopback4@1.0.0 No license field.

npm ERR! path C:\scriptGO\APIs\NODEJS\PRUEBA\ZVentas_API_LoopBack4\zventas-api-loopback4\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\scriptGO\APIs\NODEJS\PRUEBA\ZVentas_API_LoopBack4\zventas-api-loopback4\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'C:\scriptGO\APIs\NODEJS\PRUEBA\ZVentas_API_LoopBack4\zventas-api-loopback4\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\scriptGO\APIs\NODEJS\PRUEBA\ZVentas_API_LoopBack4\zventas-api-loopback4\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'C:\scriptGO\APIs\NODEJS\PRUEBA\ZVentas_API_LoopBack4\zventas-api-loopback4\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\scriptGO\APIs\NODEJS\PRUEBA\ZVentas_API_LoopBack4\zventas-api-loopback4\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'C:\scriptGO\APIs\NODEJS\PRUEBA\ZVentas_API_LoopBack4\zventas-api-loopback4\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types']
{
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\scriptGO\\APIs\\NODEJS\\PRUEBA\\ZVentas_API_LoopBack4\\zventas-api-loopback4\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types',
npm ERR!     dest: 'C:\\scriptGO\\APIs\\NODEJS\\PRUEBA\\ZVentas_API_LoopBack4\\zventas-api-loopback4\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, rename 'C:\\scriptGO\\APIs\\NODEJS\\PRUEBA\\ZVentas_API_LoopBack4\\zventas-api-loopback4\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types' -> 'C:\\scriptGO\\APIs\\NODEJS\\PRUEBA\\ZVentas_API_LoopBack4\\zventas-api-loopback4\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\scriptGO\\APIs\\NODEJS\\PRUEBA\\ZVentas_API_LoopBack4\\zventas-api-loopback4\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types',
npm ERR!   dest: 'C:\\scriptGO\\APIs\\NODEJS\\PRUEBA\\ZVentas_API_LoopBack4\\zventas-api-loopback4\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types',
npm ERR!   parent: 'loopback-connector-mssql'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lbalarezo\AppData\Roaming\npm-cache\_logs\2020-03-03T21_55_00_559Z-debug.log

**Comment by achrinza** [comment] 2020-03-04 08:21
@nsabourin @LuiguiBalarezo Thanks for the feedback, we'll look into this where possible.

<details>
<summary>Disclaimer</summary>

I'm community contributor that doesn't speak on behalf of StrongLoop or its parent company.

**Comment by stephaneerard** [comment] 2020-03-04 10:15
Same here

```
c:\test>npm install loopback-connector-mssql --save
npm WARN enoent ENOENT: no such file or directory, open 'c:\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path c:\test\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types
npm ERR! dest c:\test\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'c:\test\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'c:\test\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'c:\test\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'c:\test\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'c:\test\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'c:\test\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'c:\\test\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types',
npm ERR!     dest: 'c:\\test\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, rename 'c:\\test\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types' -> 'c:\\test\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'c:\\test\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types',
npm ERR!   dest: 'c:\\test\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types',
npm ERR!   parent: 'loopback-connector-mssql'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrateur.WIN-EBQ49A4LTJ1\AppData\Roaming\npm-cache\_logs\2020-03-04T10_11_53_942Z-debug.log

c:\test>
c:\test>npm install loopback-connector-mssql --save

```

**Comment by achrinza** [comment] 2020-03-04 10:29
@stephaneerard Thanks for providing some logs

- Error replicateable this on Windows,
- Ubuntu 180.04 LTS (via WSLv1) works fine (no error).

/cc @bajtos @raymondfeng

**Comment by stephaneerard** [comment] 2020-03-04 10:41
Running npm install loopback-connector-mssql@3.6.0 works fine

**Comment by nsabourin** [comment] 2020-03-04 14:37
@achrinza 
When I add manually version 3.6.0 in package.json and run `npm install` it doesn't work (same EPERM error as 3.7.0). But, `npm install loopback-connector-mssql@3.6.0` work's fine as @stephaneerard mentioned. Maybe this detail could help to solve the problem ?

**Comment by achrinza** [comment] 2020-03-04 15:24
@nsabourin Thanks for the additional info; I was able to replicate the issue from my end.

Unfortunately I haven't been able to find a fix for the issue yet.

In the mean time, there's 3 tested workarounds:

- Utilize Yarn 2
- Use a Non-Windows environment
- Downgrade package to `v3.6.0`

Regrettably these workarounds require some form of compromise.

I'll continue post any significant updates here.

**Comment by achrinza** [comment] 2020-03-05 03:33
Another workaround is available:

- Pull from source with the `3.7.0` commit-ish

    ```
    npm i git://github.com/strongloop/loopback-connector-mssql.git#063a7d0342f65011ad427be6f5eae4624d0a6dc3
    ```

My previous comment above has been updated to reflect this.

**Comment by achrinza** [comment] 2020-03-05 03:40
I believe I have found the issue:

- In `3.7.0`, `node_modules` was [published to the NPM registry](https://registry.npmjs.org/loopback-connector-mssql/-/loopback-connector-mssql-3.7.0.tgz).
- In `3.6.0`, `node_modules` was [**not** published to the NPM registry](https://registry.npmjs.org/loopback-connector-mssql/-/loopback-connector-mssql-3.6.0.tgz).

/cc @raymondfeng

**Comment by achrinza** [comment] 2020-03-05 04:13
I was able to replicate the issue with a local install of the [`3.7.0` tarball from the NPM registry](https://registry.npmjs.org/loopback-connector-mssql/-/loopback-connector-mssql-3.7.0.tgz):

<details>
<summary>Error logs</summary>

```bash
C:\Users\rifaa\Documents\testapp>npm i ../../Downloads/loopback-connector-mssql-3.7.0.tgz
npm WARN testapp@1.0.0 No license field.

npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Users\rifaa\Documents\testapp\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types
npm ERR! dest C:\Users\rifaa\Documents\testapp\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\rifaa\Documents\testapp\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'C:\Users\rifaa\Documents\testapp\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\Users\rifaa\Documents\testapp\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'C:\Users\rifaa\Documents\testapp\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\Users\rifaa\Documents\testapp\node_modules\loopback-connector-mssql\node_modules\.adal-node.DELETE\node_modules\@types' -> 'C:\Users\rifaa\Documents\testapp\node_modules\loopback-connector-mssql\node_modules\adal-node\node_modules\@types'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\Users\\rifaa\\Documents\\testapp\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types',
npm ERR!     dest: 'C:\\Users\\rifaa\\Documents\\testapp\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, rename 'C:\\Users\\rifaa\\Documents\\testapp\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types' -> 'C:\\Users\\rifaa\\Documents\\testapp\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\rifaa\\Documents\\testapp\\node_modules\\loopback-connector-mssql\\node_modules\\.adal-node.DELETE\\node_modules\\@types',
npm ERR!   dest: 'C:\\Users\\rifaa\\Documents\\testapp\\node_modules\\loopback-connector-mssql\\node_modules\\adal-node\\node_modules\\@types',
npm ERR!   parent: 'loopback-connector-mssql'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rifaa\AppData\Roaming\npm-cache\_logs\2020-03-05T03_59_42_725Z-debug.log
```

</details>

I tried checking out this repo at commit-ish `063a7d`, and building the tarball with `npm pack`.

- Without running `npm install` beforehand, this results in a working, installable local copy of the package. No `node_modules` was included in the generated tarball.

- Running `npm install` beforehand results in the exact issue. The `node_modules` generated by `npm install` was included.

Unfortunately I'm not involved in the publishing of this package, hence I can only guess what happened:

- `npm install` was executed before `npm publish` for `3.7.0` resulting in node_modules being packaged.

**Comment by bajtos** [comment] 2020-03-05 13:44
Thank you @achrinza for investigating the issue! I suspect the problem was introduced by https://github.com/strongloop/loopback-connector-mssql/pull/205, where we added sub-packages to `deps` where `node_modules` folders are created during `npm install` time.

I think the fix is to add fix npm configuration so that `deps/juggler-{v3,v4}/node_modules` files are not published. In my experience, it's better to use `files` entry in `package.json` (a white-list of files to include) rather than `.npmignore` (a black-list of files to exclude).

After landing the fix, we can publish a new version `3.7.1`.

I think this problem can affect other connectors that are running both juggler v3 and v4 tests.

**Comment by bajtos** [comment] 2020-03-05 15:18
If you look at loopback-connector-postgresql's `.gitignore` file, we have an entry to ignore all `node_modules` directories, see https://github.com/strongloop/loopback-connector-postgresql/blob/master/.gitignore

We use `slt-release` from https://github.com/strongloop/strong-tools to generate a changelog, create the release commit & tag, etc. This tool is creating an `.npmrc` file based on `.gitignore` file, adding few more entries that are often desired to ignore by `npm` but not by `git`.

In this repository, we have the following `.gitignore` entry:

https://github.com/strongloop/loopback-connector-mssql/blob/4f3421d658a7edb44e78eca94f7d034636622155/.gitignore#L15

I suspect it's either not honored by `npm` or the person publishing a new version of this connector did not use `slt-release`.

**Comment by bajtos** [comment] 2020-03-05 15:23
Opened a PR to fix the problem, PTAL: https://github.com/strongloop/loopback-connector-mssql/pull/225

**Comment by raymondfeng** [comment] 2020-03-05 17:24
It might have something to do with https://github.com/strongloop/loopback-connector-mssql/blob/master/package.json#L46. We had this in the past as https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime was under a restrictive license and now it's under MIT. Let's remove the prepublish script to see if it helps.

**Comment by raymondfeng** [comment] 2020-03-05 17:25
BTW, we can use `npm pack` to verify if `node_modules` are included.

**Comment by emonddr** [comment] 2020-03-05 18:10
> BTW, we can use `npm pack` to verify if `node_modules` are included.

Correct, @bajtos mentions the steps in https://github.com/strongloop/loopback-connector-mssql/pull/225 . :)

**Comment by achrinza** [comment] 2020-03-06 08:15
See also #226

**Comment by achrinza** [comment] 2020-03-14 04:42
Root cause: https://github.com/npm/cli/issues/417

Should we close the issue now that the PR has been merged?

**Comment by dhmlau** [comment] 2020-03-20 18:40
Closing as resolved. 
@Dayof, if you still encounter this issue, please feel free to open a new issue. Thanks! 

cc @emonddr

**Closed by dhmlau** 2020-03-20 18:40 UTC
Labels: bug

**Comment by Dayof** [comment] 2020-03-20 21:45
Thank you for solving the issue ! @achrinza @dhmlau @bajtos @raymondfeng 🚀
