### ISSUE TITLE
Composite keys not added as primary keys

### ISSUE THREAD

**Issue by Priminus** [strongloop/loopback-connector-mssql#138] opened 2017-04-21 10:59 UTC
# Description/Steps to reproduce

In model JSON file, I have this:
`  "properties": {
    "ContentID": {
      "type": "number",
      "required": true,
      "id": 1
    },
    "LangID": {
      "type": "number",
      "required": true,
      "id": 2
    },
    "EntityID": {
      "type": "number",
      "required": true,
      "id": 3
    },`

But when I auto-migrate, only the first column becomes a primary key.

# Expected result

In MS SQL something like this:
PK_Name | Key | Column_Name
PK_SomeName | 1 | ContentID
PK_SomeName | 2 | LangID
PK_SomeName | 3 | EntityID

Am I doing something silly?

**Comment by ssh24** [comment] 2017-05-09 20:03
@Priminus Are you trying to add all three of `ContentID`,`LangID` and `EntityID` as primary keys? The way you did it on your model definition is not correct.

Correct way to do it, is add an `id` field for each of those property and assign it to `true`.

```json
  "properties": {
    "ContentID": {
      "type": "number",
      "required": true,
      "id": true
    },
    "LangID": {
      "type": "number",
      "required": true,
      "id": true
    },
    "EntityID": {
      "type": "number",
      "required": true,
      "id": true
    }
  }
```

**Comment by Priminus** [comment] 2017-05-10 06:58
I tried "true" as well, same problem. Besides, in the documentation, using 1,2,3 is supported: https://loopback.io/doc/en/lb2/Model-definition-JSON-file.html
"In database terms, ID properties are primary key column(s) are. Such properties are defined with the ‘id’ attribute set to true or a number as the position for a composite key."

As you can see in my code fix, there was never a way to support more than 1 primary key in the ms-sql connector.

**Comment by ssh24** [comment] 2017-05-10 11:18
@Priminus Ah, I see. Do you mind creating a pull request to fix this patch? Thank you.

**Comment by Priminus** [comment] 2017-05-11 02:48
I know this is going to sound unsavoury, but I'm not going to create a pull request. I contacted Loopback and this connector can only be used as part of IBM API Connect. Since I can't use this code I've used Sequelize instead!

**Comment by ssh24** [comment] 2017-05-11 13:17
I am not sure what you mean. You can use mssql instance for free using [docker](https://hub.docker.com/r/microsoft/mssql-server-linux/).

More over, I am still not able to reproduce your issue.

Here are the reproduction steps:
#### `model.json`
```json
{
  "name": "Movies",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "ContentID": {
      "type": "number",
      "required": true,
      "id": 1
    },
    "LangID": {
      "type": "number",
      "required": true,
      "id": 2
    },
    "EntityID": {
      "type": "number",
      "required": true,
      "id": 3
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

#### script.js
```javascript
'use strict';
var async = require('async');

module.exports = function(app) {
  var mssqlDs = app.dataSources.mssqlDs;
  var Movies = app.models.Movies;

  mssqlDs.automigrate(function(err) {
    if (err) throw err;
    Movies.create({ContentID: 1, LangID: 1, EntityID: 1},
    function(err, result) {
      if (err) throw err;
      console.log('Result: ' + JSON.stringify(result));
    });
  });
};
```

#### bash output
```bash
sakibs-mac:mssql-138 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
Result: {"ContentID":1,"LangID":1,"EntityID":1}
```

#### sql output
```sql
Changed database context to 'test-db'.
ContentID   LangID      EntityID   
----------- ----------- -----------
          1           1           1

(1 rows affected)
```

Please let me know if I missed any vital steps on reproducing the issue.

**Comment by ssh24** [comment] 2017-05-15 23:39
@Priminus We have [docker](https://github.com/strongloop/loopback-connector-mssql#docker) support added for this connector. Please feel free to use it to use mssql whenever you want using that.

Closing this as it is not an issue. Feel free to reopen if needed.

**Closed by ssh24** 2017-05-15 23:39 UTC
Labels: apex, triaging
